export const restaurants = [
  {
    id: "16970",
    name: "McDonald's",
    cloudinaryImageId: "ee5f8e06b300efc07c9fe3f4df40dfc4",
    locality: "Mumbai- Pune Road",
    areaName: "Chinchwad",
    costForTwo: "₹400 for two",
    cuisines: ["Burgers", "Beverages", "Cafe", "Desserts"],
    avgRating: 4.2,
  },
  {
    id: "24435",
    name: "Domino's Pizza",
    cloudinaryImageId: "sskjrrikponrfors6kud",
    locality: "Rameera Tower",
    areaName: "Nigdi",
    costForTwo: "₹400 for two",
    cuisines: ["Pizzas", "Italian", "Pastas", "Desserts"],
    avgRating: 4.2,
  },
  {
    id: "40181",
    name: "Savali",
    cloudinaryImageId: "lbye6vascq2ggicljkkw",
    locality: "Sector 24",
    areaName: "Nigdi",
    costForTwo: "₹300 for two",
    cuisines: ["South Indian", "North Indian", "Chinese", "Biryani", "Juices"],
    avgRating: 4,
  },
  {
    id: "300961",
    name: "Kwality Walls Frozen Dessert and Ice Cream Shop",
    cloudinaryImageId: "xzzcrtbrncmbotp8goyh",
    locality: "Sainath Nagar",
    areaName: "Nigdi",
    costForTwo: "₹300 for two",
    cuisines: ["Desserts", "Ice Cream", "Ice Cream Cakes"],
    avgRating: 4.2,
  },

  {
    id: "348995",
    name: "Big Bowl (Big Bowl Company)",
    cloudinaryImageId: "992f217c2f122c0d8fc385855ca30722",
    locality: "Elpro City Square Mall",
    areaName: "Chinchwad",
    costForTwo: "₹300 for two",
    cuisines: ["North Indian", "Chinese", "Tibetan", "Desserts"],
    avgRating: 3.4,
  },
  {
    id: "373605",
    name: "Deli Belly",
    cloudinaryImageId: "2cab3b337584d36c974daa2c4bec1f2a",
    locality: "Sector 27",
    areaName: "Nigdi",
    costForTwo: "₹300 for two",
    cuisines: ["North Indian", "Chinese", "Beverages"],
    avgRating: 3.9,
  },
];
